### ISSUE TITLE
variable 'name' sames to be reserved in terraform 13

### ISSUE THREAD

**Issue by johankritzinger** [byuoitav/terraform-kubernetes-nginx-ingress-controller#12]
I've created a branch where I provide an alternative variable "ingress_name" while maintaining backwards compatibility.  I can push this branch for a PR, but don't seem to have access to do that.

johankritzinger

**Comment by bwinterton** [comment]
I just successfully deployed this module with the following config: 

```
module nginx-ingress-controller {
  source  = "git@github.com:byuoitav/terraform-kubernetes-nginx-ingress-controller?ref=master"

  name = "differentname"
  nginx_config = {
    "ssl-protocols"     = "TLSv1.2"
        "proxy-buffer-size" = "16k"
  }
  load_balancer_source_ranges = ["1.2.3.4/32"]
}
```

I don't seem to be having issues using the `name` variable. This was run on Terraform 0.13.2.

Can I get some more details on what error you are seeing?

**Comment by johankritzinger** [comment]
Apologies, I'm confused. I'm not able to replicate the error now on my local version.  I was sure I didn't have an old version of the module, but maybe I did....

**Comment by bwinterton** [comment]
No worries! Thanks for clearing this up! I'll close the issue.
