### ISSUE TITLE
Link to nginx-ingress-controller out of date.  No longer uses quay

### ISSUE THREAD

**Issue by dromazmj** [byuoitav/terraform-kubernetes-nginx-ingress-controller#8]
The latest releases of nginx-ingress-controller no longer use quay to store the image.  They have a different link to the image.

The last release to use quay is version 0.33.0. This isnt too many releases behind but this repo should be updated to make sure it can stay up to date.

Can be solved two ways
* Can the url of the image to what the latest releases use
* Expose the link to the image as an input and use that when specifying the image when creating the resource.
    - This would probably be the best approach as it would still allow users who would like to use the older versions

You can see the last images of quay to be uploaded here:
https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller?tab=tags

I would be happy to create a pull request for this.  Please let me know.

**Comment by tobiasbp** [comment]
I was running in to this issue (While wondering that the default for  version of the image was 0.29.0).
